name: My First GitHub Actions
#  a display name for your workflow. It shows up in the GitHub Actions tab

on: [push]
# the workflow runs every time code is pushed to any branch in the repository

jobs:
  build:
  #  starts a job named build. Each job is a collection of steps that run in a separate runner (virtual machine).
    runs-on: ubuntu-latest
    # the job runs on the latest version of Ubuntu provided by GitHub-hosted runners

    strategy:
      matrix:
        python-version: [3.8, 3.9]
        # tells GitHub to run the job twice, once with Python 3.8 and once with 3.9. It’s great for testing code across different environments

    steps:
    - uses: actions/checkout@v3
    #  pulls the code from your GitHub repository into the runner, so it can be used in the next steps
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
      #  installs the correct Python version (3.8 or 3.9) on the VM. ${{ matrix.python-version }} refers to the versions in the matrix above  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
      # upgrades pip and installs pytest — a popular Python testing framework — to run your test cases

    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py
      # This:
      # - Enters the src/ directory (you’re assuming your code is inside a folder named src)
      # - Runs pytest on the addition.py file (assumed to have test cases in it)

      # ⚠️ If addition.py doesn’t have test functions (like test_add()), pytest will return "no tests found."
